# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink: /:title

# Setup
title:            The Firmly Blog
tagline:          'The Firmly Blog'
description:      'Your department, company, and customers: all together now.'


author:
  name:           'Raj'
  url:            https://blog.firmly.co

paginate:         5
