title:        Firmly
tagline:      'The Firmly Blog'
description:  '.'
url:          http://firmly.co
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
