# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink: /:title

# Setup
title:            didFinishLaunchingWithOptions
tagline:          'iOS Notes From The Field'
#description:      'didFinishLaunchingWithOptions is a collection of iOS notes from the field by <a href="https://twitter.com/raj" target="_blank">@raj</a>.'
description:      'didFinishLaunchingWithOptions is a collection of programming notes from the field.'


author:
  name:           'Raj'
  url:            https://twitter.com/raj

paginate:         5
